=== andreandyp/CodigosJava/TecWeb/Segundo parcial/Practica41/Nodos anidados/xsd4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="taxonomía">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="dominio"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="dominio">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="reino"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="reino">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="phylum"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="phylum">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="clase"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="clase">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="orden"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="orden">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="familia"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="familia">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="género"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="género">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="especie"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="especie">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="subespecie" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== andreandyp/CodigosJava/TecWeb/Segundo parcial/Practica41/Nodos anidados/xml4.xml
<?xml version="1.0" encoding="UTF-8"?>
<taxonomía xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd4.xsd">
  <dominio>
    <reino>
      <phylum>
        <clase>
          <orden>
            <familia>
              <género>
                <especie>
                  <subespecie/>
                </especie>
              </género>
            </familia>
          </orden>
        </clase>      
      </phylum>    
    </reino>
  </dominio>
</taxonomía>
