=== andreandyp/CodigosJava/ProyectoWeb/web/esquemalogin.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" >
  <xs:element name="usuarios">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="usuario" maxOccurs="unbounded" minOccurs="0">
           <xs:complexType>
                <xs:sequence>
                <xs:element name="nombre"  type="xs:string" minOccurs="1" />
                <xs:element name="correo" type="xs:string" minOccurs="1" />
                <xs:element name="n_usuario" type="xs:string" minOccurs="1" />
                <xs:element name="pass" type="xs:string" minOccurs="1" />                          
                </xs:sequence>        
            <xs:attribute name="id" type="xs:string" use="required" />
            <xs:attribute name="tipo" type="xs:string" use="required" />
           </xs:complexType>        
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== andreandyp/CodigosJava/TecWeb/ProyectoWeb/build/web/xml_login.xml
<?xml version="1.0" encoding="UTF-8"?>
<usuarios xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="esquemalogin.xsd">
  <usuario id="1" tipo="administrador">
    <nombre>Alicia</nombre>
    <correo>ornelas@escom.com</correo>
    <n_usuario>zandy3</n_usuario>
    <pass>zandy3</pass>
  </usuario>
  <usuario id="2" tipo="profesor">
    <nombre>ruben</nombre>
    <correo>peredo@gmail.com</correo>
    <n_usuario>rperedo</n_usuario>
    <pass>123peredo</pass>
  </usuario>
  <usuario id="3" tipo="administrador">
    <nombre>Rodrigo Andres</nombre>
    <correo>rodrigo@live.com</correo>
    <n_usuario>andii_burciaga</n_usuario>
    <pass>rodrigoandres</pass>
  </usuario>
  <usuario id="4" tipo="profesor">
    <nombre>sergio</nombre>
    <correo>multi@gmail.com</correo>
    <n_usuario>sergio_b</n_usuario>
    <pass>sergiob</pass>
  </usuario>
  <usuario id="5" tipo="estudiante">
    <nombre>Juan</nombre>
    <correo>juan@live.com</correo>
    <n_usuario>juan</n_usuario>
    <pass>123</pass>
  </usuario>
</usuarios>

=== andreandyp/CodigosJava/ProyectoWeb/web/xml_login.xml
<?xml version="1.0" encoding="UTF-8"?>
<usuarios xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="esquemalogin.xsd">
  <usuario id="1" tipo="administrador">
    <nombre>Alicia</nombre>
    <correo>ornelas@escom.com</correo>
    <n_usuario>zandy3</n_usuario>
    <pass>zandy3</pass>
  </usuario>
  <usuario id="2" tipo="profesor">
    <nombre>ruben</nombre>
    <correo>peredo@gmail.com</correo>
    <n_usuario>rperedo</n_usuario>
    <pass>123peredo</pass>
  </usuario>
  <usuario id="3" tipo="administrador">
    <nombre>Rodrigo AndrÃ©s</nombre>
    <correo>rodrigo@live.com</correo>
    <n_usuario>andii_burciaga</n_usuario>
    <pass>rodrigoandres</pass>
  </usuario>
</usuarios>
