=== andreandyp/CodigosJava/TecWeb/Segundo parcial/Practica41/Mix/xsd3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="alimentos">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="bebidas"/>
      </xs:sequence>
      <xs:attribute name="solobebidas" type="xs:boolean" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="bebidas">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element name="alcohol" type="xs:string" maxOccurs="4"/>
        <xs:element name="agua" type="xs:string" maxOccurs="4"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== andreandyp/CodigosJava/TecWeb/Segundo parcial/Practica41/Mix/xml3.xml
<?xml version="1.0" encoding="UTF-8"?>
<alimentos solobebidas="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd3.xsd">
  <bebidas>
    Son sólo ejemplos
    <alcohol>Tequila</alcohol>  
    <alcohol>Cerveza</alcohol>
    <alcohol>Vodka</alcohol>
    <agua>Simple</agua>
    <agua>Limon</agua>
    <agua>Jamaica</agua>
  </bebidas>
</alimentos>
