=== andreandyp/CodigosJava/TecWeb/Segundo parcial/Practica41/Mix/xsd5.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="html">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="head"/>
        <xs:element ref="body"/>
        <xs:element ref="script" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="lang" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="head">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded">
        <xs:element ref="meta"/>
        <xs:element name="title" type="xs:string"/>
        <xs:element ref="link"/>
        <xs:element name="style" type="xs:string"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="meta">
    <xs:complexType>
      <xs:attribute name="content" type="xs:string" use="required"/>
      <xs:attribute name="http-equiv" type="xs:string"/>
      <xs:attribute name="name" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="link">
    <xs:complexType>
      <xs:attribute name="href" type="xs:string" use="required"/>
      <xs:attribute name="hreflang" type="xs:string"/>
      <xs:attribute name="id" type="xs:string"/>
      <xs:attribute name="rel" type="xs:string" use="required"/>
      <xs:attribute name="type" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="body">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="div"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="div">
    <xs:complexType mixed="true">
      <xs:choice maxOccurs="unbounded" minOccurs="0">
        <xs:element ref="a"/>
        <xs:element name="hr" type="xs:string"/>
        <xs:element ref="nav"/>
        <xs:element ref="h2"/>
        <xs:element name="h1" type="xs:string"/>
        <xs:element ref="p"/>
        <xs:element name="br" type="xs:string"/>
        <xs:element name="h3" type="xs:string"/>
        <xs:element ref="div"/>
        <xs:element ref="img"/>
        <xs:element ref="button"/>
        <xs:element ref="ul"/>
        <xs:element ref="h4"/>
      </xs:choice>
      <xs:attribute name="class" type="xs:string"/>
      <xs:attribute name="id" type="xs:string"/>
      <xs:attribute name="role" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="button">
    <xs:complexType mixed="true">
      <xs:sequence minOccurs="0">
        <xs:element ref="span" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="class" type="xs:string" use="required"/>
      <xs:attribute name="data-dismiss" type="xs:string"/>
      <xs:attribute name="data-target" type="xs:string"/>
      <xs:attribute name="data-toggle" type="xs:string"/>
      <xs:attribute name="onclick" type="xs:string"/>
      <xs:attribute name="type" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="h4">
    <xs:complexType mixed="true">
      <xs:attribute name="class" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="p">
    <xs:complexType mixed="true">
      <xs:sequence minOccurs="0">
        <xs:element ref="a" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="nav">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="div"/>
      </xs:sequence>
      <xs:attribute name="class" type="xs:string" use="required"/>
      <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="span">
    <xs:complexType>
      <xs:attribute name="class" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="a">
    <xs:complexType mixed="true">
      <xs:sequence minOccurs="0">
        <xs:element ref="img" minOccurs="0"/>
        <xs:element ref="span" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="class" type="xs:string"/>
      <xs:attribute name="data-target" type="xs:string"/>
      <xs:attribute name="data-toggle" type="xs:string"/>
      <xs:attribute name="href" type="xs:string"/>
      <xs:attribute name="onclick" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="ul">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="li" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="class" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="li">
    <xs:complexType mixed="true">
      <xs:sequence minOccurs="0">
        <xs:element ref="a" minOccurs="0"/>
        <xs:element ref="ul" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="class" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="img">
    <xs:complexType>
      <xs:attribute name="alt" type="xs:string" use="required"/>
      <xs:attribute name="class" type="xs:string" use="required"/>
      <xs:attribute name="id" type="xs:string"/>
      <xs:attribute name="src" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="h2">
    <xs:complexType mixed="true">
      <xs:sequence minOccurs="0">
        <xs:element ref="img" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="data-target" type="xs:string"/>
      <xs:attribute name="data-toggle" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="script">
    <xs:complexType mixed="true">
      <xs:attribute name="src" type="xs:string"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== andreandyp/CodigosJava/TecWeb/Segundo parcial/Practica40/Mix/xml5.xml
<?xml version="1.0" encoding="UTF-8"?>
<html lang="es" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd5.xsd">
	<head>
		<!--Metadatos-->
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"/>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<meta http-equiv="Cache-control" content="max-age=600"/>
		<!--Bibliotecas jQuery, Boostrap y las fuentes-->
		<title>Bienvenido a mi página web - AndreAndyP</title>
		<link rel="icon" type="image/jpg" href="imagenes/favicon.png"/>
		<link href="css/bootstrap.min.css" rel="stylesheet"/>
    	<style>
			#foto1{width: 100%; height: 100%;}
			h2{text-align: center;}
			p{text-align: justify;}
			body{color: white;}
			button{border: none;background: inherit;}
			.fijo{position: fixed;right: 0px;border-left: solid white;border-top: solid white;border-bottom: solid white;}
			.jumbotron{background-color: inherit;}
			.flecha{margin: 0 auto;}
			.iconos{margin: 2px 5px 0px 0px;}
		</style>
		<link id="modo" href="css/normal.css" rel="stylesheet"/>
		<link rel="alternate" hreflang="eo" href="internacional/esperanto-eo.html"/>
	</head>
	<body>
		<div id="fondo">
			<div class="modal fade" id="aviso" role="dialog">
				<div class="modal-dialog modal-lg">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal">x</button>
							<h4 class="modal-title">Traducciones a idiomas no disponbles</h4>
						</div>
						<div class="modal-body">
							<p>Más idiomas se añadirán pronto. Puedes solicitar nuevas traducciones envíandome un tuit.</p>
						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
						</div>
					</div>
				</div>
			</div>
			<hr></hr>
			<nav class="navbar navbar-inverse navbar-fixed-bottom" id="menu">
			<div class="container-fluid">
				<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#barra">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand">Contacto y ajustes</a>
				</div>
				<div class="collapse navbar-collapse" id="barra">
				<ul class="nav navbar-nav">
					<li class="dropdown">
						<a class="dropdown-toggle" data-toggle="dropdown" href="#">¡Contacta conmigo!<span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li><a href="https://www.facebook.com/AndreAndyP"><img class="iconos" src="imagenes/f.png" alt="Bloqueame esta Adblock"/>Facebook</a></li>
							<li><a href="https://twitter.com/AndreAndyP"><img class="iconos" src="imagenes/t.png" alt="Bloqueame esta Adblock"/>Twitter</a></li>
							<li><a href="mailto:andreandyp@outlook.com"><img class="iconos" src="imagenes/correo.png" alt="Correo electrónico"/>Correo electrónico</a></li>
						</ul>
					</li>
					<li class="dropdown">
						<a class="dropdown-toggle" data-toggle="dropdown" href="#">Información adicional<span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li><a href="https://github.com/andreandyp"><img class="iconos" src="imagenes/github.png" alt="github"/>Github</a></li>
							<li><a href="https://mx.linkedin.com/in/andreandyp"><img class="iconos" src="imagenes/lin.png" alt="Bloqueame esta Adblock"/>LinkedIn</a></li>
							<li><a href="https://www.duolingo.com/andreandyp"><img class="iconos" src="imagenes/mundo.png" alt="Mundo"/>Duolingo</a></li>
						</ul>
					</li>
					<li class="dropdown">
						<a class="dropdown-toggle" data-toggle="dropdown" href="#">Traducir...<span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li><a href="internacional/esperanto-eo.html">Esperanto (Esperanto)</a></li>
      						<li class="divider"></li>
      						<li><a href="#" data-toggle="modal" data-target="#aviso">Otros</a></li>
						</ul>
					</li>
					<li><a href="#" class="noche" onclick="cambiar('es')">¡Apagar luces!</a></li>
				</ul>
				</div>
			</div>
			</nav>
			<div class="container-fluid">		
				<div class="row">
					<div class="col-xs-12 col-sm-10 col-md-10 col-lg-10">
						<div class="row">
							<div class="col-xs-12 col-sm-10 col-md-10 col-lg-10">
								<div class="jumbotron">
									<h1>Hola, yo soy André Michel. Bienvenido.</h1>
									<p>Desarrollador, esperantista, en contra del sexismo. Baja y conóceme.</p>
								</div>
							</div>
							<div class="col-xs-6 col-xs-offset-3 col-sm-offset-0 col-sm-2 col-md-2 col-lg-2">
								<img src="imagenes/ima1.jpg" class="responsive" alt="Foto" id="foto1" />
							</div>
						</div>
						<hr></hr>
						<div class="row">
							<div class="col-sm-6 col-md-6 col-lg-6">
								<h2 data-toggle="collapse" data-target="#a1">Acerca de mí.	<img src="imagenes/flecha.png" class="flecha" alt="flecha"/></h2>
								<div id="a1" class="collapse in">
									<p>Mi nombre es André Michel, soy estudiante de Ingeniería en Sistemas Computacionales en la Escuela Superior de Cómputo del Instituto Politénico Nacional. Tengo 18 años, soy mexicano y vivo en la Ciudad de México.</p>
									<p>Me gusta programar, los idiomas, debatir, bailar, leer, ponerle de mi parte a lo que hago, aprender cosas nuevas y salir a pasear. No me gusta el sexismo, el uso incorrecto de la lengua, el conformismo, los límites y la ignorancia.</p>
									<p>Soy una persona tranquila en general, aunque suelo ser un poco explosivo. No me gusta pelear y trato de llevarme bien con todos. Mientras no me hagan nada, yo no haré nada a nadie. Creo en teorías conspiracionales y en Dios (soy católico).</p>
								</div>
							</div>
							<div class="col-sm-6 col-md-6 col-lg-6">
								<h2 data-toggle="collapse" data-target="#a2">Metas personales y profesionales. 	<img src="imagenes/flecha.png" class="flecha" alt="flecha"/></h2>
								<div id="a2" class="collapse in">
									<p>Tengo muchas metas planteadas. Mi plan a corto plazo es terminar la carrera en 4 años, obtener experiencia laboral, así como seguir desarrollándome profesionalmente. A mediano plazo, quiero obtener un trabajo en una empresa multinacional de tecnología con sede en México, como Microsoft, Google o Apple. Finalmente, a muy largo plazo, me gustaría estudiar una segunda carrera relacionada con los idiomas o estudiar un posgrado en Ciencias de la Computación.</p>
									<p>Por supuesto, también tengo metas personales. Por ahora, quiero seguir creciendo como persona, conociendo de la vida. Después, quiero irme a vivir solo y/o comprar un coche eléctrico, preferentemente un Tesla Modelo S. Quiero viajar a Chile, Brasil, España y Canadá, así como el resto de mi país. Finalmente, al igual que muchos, quiero casarme y tener hijos, pero hasta después de los 30 años de edad.</p>
								</div>
							</div>
						</div>
						<hr></hr>
						<div class="row">
							<div class="col-sm-6 col-md-6 col-lg-6">
								<h2 data-toggle="collapse" data-target="#b1">Libros y sitios web que recomiendo.	<img src="imagenes/flecha.png" class="flecha" alt="flecha"/></h2>
								<div id="b1" class="collapse in">
									<p>Libros:</p>
									<ul>
										<li>Segunda estrella a la derecha - Deborah Hautzig.</li>
										<li>Cien años de soledad - Gabriel García Márquez.</li>
										<li>Esperanto y comunicación humana - María Isabel Nájera Sepúlveda.</li>
										<li>Historia de cronopios y de famas - Julio Cortázar.</li>
										<li>Pregúntale a Alicia - Anónimo.</li>
									</ul>
									<p>Sitios web:</p>
									<ul>
										<li><a href="http://mva.microsoft.com">Microsoft Virtual Academy.</a></li>
										<li><a href="http://www.xataka.com.mx/">Xataka México.</a></li>
										<li><a href="https://www.duolingo.com">Duolingo.</a></li>
										<li><a href="http://www.justdancenow.com">Just Dance Now.</a></li>
										<li><a href="https://www.toptal.com/handbook">Manual en línea del Ingeniero de Software (en inglés).</a></li>
									</ul>
								</div>
							</div>
							<div class="col-sm-6 col-md-6 col-lg-6">
								<h2 data-toggle="collapse" data-target="#b2">Lenguajes de programación e idiomas.	<img src="imagenes/flecha.png" class="flecha" alt="flecha"/></h2>
								<div id="b2" class="collapse in">
									<p>Idiomas:</p>
									<ul>
										<li>Español: nativo.</li>
										<li>Inglés: nivel A2 (MCER). Hablo, leo y escribo.</li>
										<li>Esperanto: básico. Leo y escribo.</li>
										<li>Conocimientos muy básicos en francés, portugués y náhuatl.</li>
									</ul>
									<p>Lenguajes de programación:</p>
									<ul>
										<li>Java: medio.</li>
										<li>C#: medio.</li>
										<li>Javascript: básico.</li>
										<li>Conocimientos muy básicos en Go, SQL y C.</li>
									</ul>
								</div>
							</div>
						</div>
						<hr></hr>
						<div class="row">
							<div class="col-sm-6 col-md-6 col-lg-6">
								<h2 data-toggle="collapse" data-target="#c1">Íconos de Flaticon.es	<img src="imagenes/flecha.png" class="flecha" alt="flecha"/></h2>
								<div id="c1" class="collapse in">
									Ícono de Facebook hecho por <a href="http://www.flaticon.es/autores/linh-pham">Linh Pham</a><br/>
									Ícono de Twitter hecho por <a href="http://www.flaticon.es/autores/linh-pham">Linh Pham</a><br/>
									Ícono de Correo electrónico hecho por <a href="http://www.flaticon.es/autores/sebastien-gabriel">Sebastien Gabriel</a><br/>
									Ícono de Github hecho por <a href="http://www.flaticon.es/autores/zurb">Zurb</a><br/>
									Ícono de LinkedIn hecho por <a href="http://www.flaticon.es/autores/alessio-atzeni">Alessio Atzeni</a><br/>
									Ícono de Planeta hecho por <a href="http://www.flaticon.es/autores/freepik">Freepik</a><br/>
									Ícono de Traducción hecho por <a href="http://www.flaticon.es/autores/freepik">Freepik</a><br/>
