=== andreandyp/CodigosJava/TecWeb/Segundo parcial/Practica36/dtd5.dtd
<!ELEMENT lenguajes (Romance, Germano, Eslavo, Amerindio, Artificial*)>
<!ELEMENT Romance (lenguaje+)>
<!ELEMENT lenguaje (#PCDATA)>
<!ATTLIST lenguaje
          variante CDATA #REQUIRED>
<!ELEMENT Germano (lenguaje+)>
<!ELEMENT Eslavo (lenguaje*)>
<!ELEMENT Amerindio (lenguaje+)>
<!ELEMENT Artificial (#PCDATA)>

=== andreandyp/CodigosJava/TecWeb/Segundo parcial/Practica36/xml5.xml
<?xml version='1.0' encoding='UTF-8' ?> 
<!DOCTYPE lenguajes SYSTEM "dtd5.dtd">
<lenguajes>
  <Romance>
    <lenguaje variante="México">Español</lenguaje>  
    <lenguaje variante="España">Español</lenguaje>  
    <lenguaje variante="Francia">Francés</lenguaje>  
    <lenguaje variante="Canadá">Francés</lenguaje>  
  </Romance>
  <Germano>
    <lenguaje variante="Alemania">Alemán</lenguaje>  
    <lenguaje variante="Gran Bretaña">Inglés</lenguaje>
    <lenguaje variante="Australia">Inglés</lenguaje>
  </Germano>
  <Eslavo>

  </Eslavo>
  <Amerindio>
    <lenguaje variante="Yucatan">Maya</lenguaje>  
    <lenguaje variante="Centroamérica">Maya</lenguaje>  
  </Amerindio>
</lenguajes>
